---
title: Radiant -- Business analytics using R and Shiny
---

Radiant is a platform-independent browser-based interface for business analytics in [R](https://www.r-project.org/), based on the [Shiny](https://www.rstudio.com/shiny/) package. Developed by <a href="http://rady.ucsd.edu/faculty/directory/nijs/" target="_blank">Vincent Nijs</a>. Please use the issue tracker on GitHub to suggest enhancements or report problems: <a href="https://github.com/radiant-rstats/radiant/issues" _target="_blank">https://github.com/radiant-rstats/radiant/issues</a>. For other questions and comments please use radiant@rady.ucsd.edu.

> **Note:** User profiles (or user names or logins) containing non-ASCII characters may cause problems during installation. To address this issue please use a profile name (login) that contains ASCII (A-Z, a-z) letters and numbers only. For example, c:\\users\\myprofilename

## Installing Radiant on Windows

For Windows, download and run the all-in-one installer for <a href="http://rady.ucsd.edu/faculty/directory/nijs/pub/docs/radiant/Rady-Radiant-Installer-64bit.exe">R, Rstudio, and Radiant</a>. For a video tutorial see the `Install Radiant on Windows` video below:

<iframe width="640" height="375" src="https://www.youtube.com/embed/iaB4mTrm2Co" frameborder="0" allowfullscreen></iframe>

> Credits: Thanks go to Brandon Salas at the Rady School of Management for creating the Windows installer

## Installing Radiant on Mac

For Mac, first download and install R from <a href="https://cran.r-project.org/bin/macosx/" target="_blank">https://cran.r-project.org/bin/macosx/</a>. After R has been installed, open R, copy-and-paste the command below into R, and press return. Accept all default settings during the install process:

```r
source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install.R")
```

For a video tutorial see the `Install Radiant on Mac` video below:

<iframe width="640" height="375" src="https://www.youtube.com/embed/WheqHpobMZg" frameborder="0" allowfullscreen></iframe>

## Use a modern browser

For example, [Chrome](https://www.google.com/intl/en/chrome/browser/desktop/) or Safari. Internet Explorer (version 11 or higher) should also work but Chrome is the recommended browser. Most browsers will, by default, save downloads to the downloads folder. However, when using Radiant it is more convenient if the browser asks you where to save files. In Chrome got to _Preferences > Advanced preferences > Downloads_ and then check the "Ask where to save each file before downloading" box.

## Starting Radiant

I recommend you use Rstudio to run the Radiant application. When you open Rstudio you can start and update Radiant through the `Addins` menu at the top of the screen. When Radiant starts you will see data on diamond prices. To close the application click the <i title='Power off' class='fa fa-power-off'></i> icon in the navigation bar and then click `Stop`. The Radiant process will stop and the browser window will close (Chrome) or gray-out.

## Installing additional R-development tools

To install additional development tools (i.e., Rtools, git, homebrew) copy-and-paste the command below into R or Rstudio and press return. When installing Rtools, Windows users should add Rstools to the system path.

```r
source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/install_dev.R")
```

## Documentation

Documentation and tutorials for each of the apps are available at <https://radiant-rstats.github.io/docs/> and in the Radiant web interface (the <i title='Help' class='fa fa-edit'></i> icons on each page and the <i title='Help' class='fa fa-question-circle'></i> icon in the navigation bar).

Want more help getting started? Watch the tutorials on the [documentation site](https://radiant-rstats.github.io/docs/tutorials.html).

## Trouble shooting

Windows users may need to start R and Rstudio `as administrator`. On rare occasions R(studio) may complain that a package is not yet installed when starting Radiant. If so, install the package mentioned using the command below but replace 'package-that-is-not-yet-installed' with the package name mentioned in the error message

```r
install.packages("package-that-is-not-yet-installed", repos = "https://cran.rstudio.com", type = "binary")
```

or copy-and-paste the command below into R to check if any required packages have not yet been installed

```r
source("https://raw.githubusercontent.com/radiant-rstats/minicran/gh-pages/update.R")
```

## Reporting issues

Rady students can report any issues they might have with Radiant on Piazza. Otherwise, please use the GitHub issue tracker at <a href="https://github.com/radiant-rstats/radiant/issues" target="_blank">github.com/radiant-rstats/radiant/issues</a>.
